/**
 * Döviz kodu → { ad (Türkçe), cc (ISO 3166-1 alpha-2, flag-icons için) }
 * flag-icons kullanımı: <span className={`fi fi-${cc}`} />
 */
export const FX_META = {
  USD: { ad: 'ABD Doları',                   cc: 'us' },
  EUR: { ad: 'Euro',                          cc: 'eu' },
  GBP: { ad: 'İngiliz Sterlini',              cc: 'gb' },
  CHF: { ad: 'İsviçre Frangı',               cc: 'ch' },
  JPY: { ad: 'Japon Yeni',                    cc: 'jp' },
  AUD: { ad: 'Avustralya Doları',             cc: 'au' },
  CAD: { ad: 'Kanada Doları',                cc: 'ca' },
  NZD: { ad: 'Yeni Zelanda Doları',          cc: 'nz' },
  SGD: { ad: 'Singapur Doları',              cc: 'sg' },
  HKD: { ad: 'Hong Kong Doları',             cc: 'hk' },
  DKK: { ad: 'Danimarka Kronu',              cc: 'dk' },
  SEK: { ad: 'İsveç Kronu',                  cc: 'se' },
  NOK: { ad: 'Norveç Kronu',                cc: 'no' },
  PLN: { ad: 'Polonya Zlotısı',              cc: 'pl' },
  CZK: { ad: 'Çek Korunası',                cc: 'cz' },
  HUF: { ad: 'Macar Forinti',               cc: 'hu' },
  RON: { ad: 'Rumen Leyi',                   cc: 'ro' },
  BGN: { ad: 'Bulgar Levası',               cc: 'bg' },
  HRK: { ad: 'Hırvat Kunası',               cc: 'hr' },
  RSD: { ad: 'Sırp Dinarı',                 cc: 'rs' },
  ISK: { ad: 'İzlanda Kronası',             cc: 'is' },
  MKD: { ad: 'Makedon Dinarı',              cc: 'mk' },
  BAM: { ad: 'Bosna Markı',                 cc: 'ba' },
  SAR: { ad: 'Suudi Arabistan Riyali',       cc: 'sa' },
  AED: { ad: 'BAE Dirhemi',                 cc: 'ae' },
  KWD: { ad: 'Kuveyt Dinarı',               cc: 'kw' },
  QAR: { ad: 'Katar Riyali',               cc: 'qa' },
  BHD: { ad: 'Bahreyn Dinarı',              cc: 'bh' },
  OMR: { ad: 'Umman Riyali',               cc: 'om' },
  JOD: { ad: 'Ürdün Dinarı',               cc: 'jo' },
  IQD: { ad: 'Irak Dinarı',                cc: 'iq' },
  EGP: { ad: 'Mısır Poundu',               cc: 'eg' },
  MAD: { ad: 'Fas Dirhemi',                cc: 'ma' },
  TND: { ad: 'Tunus Dinarı',               cc: 'tn' },
  DZD: { ad: 'Cezayir Dinarı',             cc: 'dz' },
  LYD: { ad: 'Libya Dinarı',               cc: 'ly' },
  ILS: { ad: 'İsrail Şekeli',              cc: 'il' },
  LBP: { ad: 'Lübnan Poundu',              cc: 'lb' },
  SYP: { ad: 'Suriye Poundu',              cc: 'sy' },
  IRR: { ad: 'İran Riyali',                cc: 'ir' },
  YER: { ad: 'Yemen Riyali',               cc: 'ye' },
  ZAR: { ad: 'Güney Afrika Randı',          cc: 'za' },
  NGN: { ad: 'Nijerya Nayrası',             cc: 'ng' },
  KES: { ad: 'Kenya Şilini',               cc: 'ke' },
  GHS: { ad: 'Gana Sedisi',                cc: 'gh' },
  ETB: { ad: 'Etiyopya Birri',             cc: 'et' },
  TZS: { ad: 'Tanzanya Şilini',            cc: 'tz' },
  UGX: { ad: 'Uganda Şilini',              cc: 'ug' },
  RWF: { ad: 'Ruanda Frangı',              cc: 'rw' },
  SDG: { ad: 'Sudan Poundu',               cc: 'sd' },
  CDF: { ad: 'Kongo Frangı',               cc: 'cd' },
  CVE: { ad: 'Yeşil Burun Escudosu',       cc: 'cv' },
  DJF: { ad: 'Cibuti Frangı',              cc: 'dj' },
  ERN: { ad: 'Eritre Nakfası',             cc: 'er' },
  GMD: { ad: 'Gambiya Dalasisi',           cc: 'gm' },
  GNF: { ad: 'Gine Frangı',               cc: 'gn' },
  KMF: { ad: 'Komorlar Frangı',            cc: 'km' },
  LRD: { ad: 'Liberya Doları',             cc: 'lr' },
  LSL: { ad: 'Lesoto Lotisi',              cc: 'ls' },
  MGA: { ad: 'Madagaskar Ariarisi',        cc: 'mg' },
  MRU: { ad: 'Moritanya Ugiyası',          cc: 'mr' },
  MUR: { ad: 'Mauritius Rupisi',           cc: 'mu' },
  MWK: { ad: 'Malavi Kvaçası',             cc: 'mw' },
  MZN: { ad: 'Mozambik Metikali',          cc: 'mz' },
  NAD: { ad: 'Namibya Doları',             cc: 'na' },
  SCR: { ad: 'Seyşeller Rupisi',           cc: 'sc' },
  SLE: { ad: 'Sierra Leone Leonesi',       cc: 'sl' },
  SOS: { ad: 'Somali Şilini',              cc: 'so' },
  SSP: { ad: 'Güney Sudan Poundu',         cc: 'ss' },
  STN: { ad: 'São Tomé Dobrası',           cc: 'st' },
  SZL: { ad: 'Svaziland Lilangenisi',      cc: 'sz' },
  ZMW: { ad: 'Zambiya Kvaçası',            cc: 'zm' },
  CNY: { ad: 'Çin Yuanı',                  cc: 'cn' },
  CNH: { ad: 'Çin Yuanı (Offshore)',       cc: 'cn' },
  INR: { ad: 'Hindistan Rupisi',           cc: 'in' },
  KRW: { ad: 'Güney Kore Wonu',            cc: 'kr' },
  IDR: { ad: 'Endonezya Rupisi',           cc: 'id' },
  MYR: { ad: 'Malezya Ringgiti',           cc: 'my' },
  THB: { ad: 'Tayland Bahtı',             cc: 'th' },
  PHP: { ad: 'Filipin Pesosu',            cc: 'ph' },
  VND: { ad: 'Vietnam Dongu',             cc: 'vn' },
  PKR: { ad: 'Pakistan Rupisi',            cc: 'pk' },
  BDT: { ad: 'Bangladeş Takası',          cc: 'bd' },
  LKR: { ad: 'Sri Lanka Rupisi',          cc: 'lk' },
  NPR: { ad: 'Nepal Rupisi',              cc: 'np' },
  MMK: { ad: 'Myanmar Kyatı',             cc: 'mm' },
  KHR: { ad: 'Kamboçya Rieli',            cc: 'kh' },
  LAK: { ad: 'Laos Kipi',                 cc: 'la' },
  TWD: { ad: 'Tayvan Doları',             cc: 'tw' },
  MNT: { ad: 'Moğolistan Tugriki',        cc: 'mn' },
  MOP: { ad: 'Makao Patakası',            cc: 'mo' },
  MVR: { ad: 'Maldiv Rufiyası',           cc: 'mv' },
  BTN: { ad: 'Bhutan Ngultrumu',          cc: 'bt' },
  BND: { ad: 'Brunei Doları',             cc: 'bn' },
  AZN: { ad: 'Azerbaycan Yeni Manatı',    cc: 'az' },
  KZT: { ad: 'Kazakistan Tengesi',        cc: 'kz' },
  UZS: { ad: 'Özbekistan Somu',           cc: 'uz' },
  TJS: { ad: 'Tacikistan Somonisi',       cc: 'tj' },
  TMT: { ad: 'Türkmenistan Manatı',       cc: 'tm' },
  GEL: { ad: 'Gürcistan Larisi',          cc: 'ge' },
  AMD: { ad: 'Ermeni Dramı',              cc: 'am' },
  KGS: { ad: 'Kırgızistan Somu',          cc: 'kg' },
  RUB: { ad: 'Rus Rublesi',               cc: 'ru' },
  UAH: { ad: 'Ukrayna Grivnası',          cc: 'ua' },
  BYN: { ad: 'Belarus Rublesi',           cc: 'by' },
  MDL: { ad: 'Moldova Leyi',              cc: 'md' },
  BRL: { ad: 'Brezilya Reali',            cc: 'br' },
  MXN: { ad: 'Meksika Pesosu',            cc: 'mx' },
  ARS: { ad: 'Arjantin Pesosu',           cc: 'ar' },
  CLP: { ad: 'Şili Pesosu',              cc: 'cl' },
  COP: { ad: 'Kolombiya Pesosu',          cc: 'co' },
  PEN: { ad: 'Peru Solu',                 cc: 'pe' },
  UYU: { ad: 'Uruguay Pesosu',            cc: 'uy' },
  BOB: { ad: 'Bolivya Bolivyanosu',       cc: 'bo' },
  PYG: { ad: 'Paraguay Guaranisi',        cc: 'py' },
  VES: { ad: 'Venezuela Bolivarı',        cc: 've' },
  CRC: { ad: 'Kosta Rika Kolonu',         cc: 'cr' },
  GTQ: { ad: 'Guatemala Quetzalı',        cc: 'gt' },
  HNL: { ad: 'Honduras Lempirası',        cc: 'hn' },
  DOP: { ad: 'Dominik Pesosu',            cc: 'do' },
  JMD: { ad: 'Jamaika Doları',            cc: 'jm' },
  TTD: { ad: 'Trinidad Doları',           cc: 'tt' },
  BBD: { ad: 'Barbados Doları',           cc: 'bb' },
  BSD: { ad: 'Bahama Doları',             cc: 'bs' },
  BZD: { ad: 'Belize Doları',             cc: 'bz' },
  GYD: { ad: 'Guyana Doları',             cc: 'gy' },
  SRD: { ad: 'Surinam Doları',            cc: 'sr' },
  PAB: { ad: 'Panama Balboası',           cc: 'pa' },
  NIO: { ad: 'Nikaragua Kordobası',       cc: 'ni' },
  HTG: { ad: 'Haiti Gurdu',              cc: 'ht' },
  FJD: { ad: 'Fiji Doları',              cc: 'fj' },
  PGK: { ad: 'Papua Yeni Gine Kinası',   cc: 'pg' },
  TOP: { ad: 'Tonga Paangası',           cc: 'to' },
  VUV: { ad: 'Vanuatu Vatusu',           cc: 'vu' },
  WST: { ad: 'Samoa Talası',             cc: 'ws' },
  TRY: { ad: 'Türk Lirası',              cc: 'tr' },
  AFN: { ad: 'Afgan Afganisi',           cc: 'af' },
  ALL: { ad: 'Arnavut Leki',             cc: 'al' },
  AWG: { ad: 'Aruba Florini',            cc: 'aw' },
  BMD: { ad: 'Bermuda Doları',           cc: 'bm' },
  BWP: { ad: 'Botsvana Pulası',          cc: 'bw' },
  FKP: { ad: 'Falkland Adaları Poundu',  cc: 'fk' },
  GIP: { ad: 'Cebelitarık Poundu',       cc: 'gi' },
  KYD: { ad: 'Cayman Adaları Doları',   cc: 'ky' },
  SHP: { ad: 'Saint Helena Poundu',      cc: 'sh' },
  ANG: { ad: 'Hollanda Antil Guldeni',   cc: 'cw' },
};

/** flag-icons span bileşeni */
export function FlagImg({ cc, size = 24 }) {
  if (!cc) {
    return (
      <span
        className="inline-block bg-gray-200 rounded-sm flex-shrink-0"
        style={{ width: size, height: Math.round(size * 0.667) }}
      />
    );
  }
  return (
    <span
      className={`fi fi-${cc} flex-shrink-0`}
      style={{
        width: size,
        height: Math.round(size * 0.667),
        display: 'inline-block',
        backgroundSize: 'cover',
        borderRadius: 2,
      }}
    />
  );
}
